name: n88
channels:
  - friedchickean
  - defaults
dependencies:
  - python >=3.7
  - cmake >=3.30.3
  - boost >=1.56
  - ninja
  - gtest
  - libnetcdf >=4.8, <=4.8.1
  - pqctio
  - aimio
  - vtk >=9.0.3, <= 9.4.1
  - tbb-devel
  - nose
