name: n88
channels:
  - friedchickean
  - defaults
dependencies:
  - python >=3.7
  - cmake >=3.30.3
  - boost =1.8.5
  - ninja
  - gtest
  - libnetcdf =4.9.2
  - pqctio
  - aimio
  - vtk
  - tbb-devel
  - nose
  - pugixml =1.11.4
  - n88util
