package:
  name: vtkbone
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0
  string: "py{{ CONDA_PY }}"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.12
    - ninja
    - gtest
    - boost =1.85.0
    - python =3.10
    - libnetcdf >=4.8
    - pqctio
    - aimio
    - vtk =9.3.1
    - tbb-devel
    - nose
    - pugixml
    - n88util
  host:
    - vtk =9.3.1
  run:
    - python =3.10
    - boost =1.85.0
    - libnetcdf >=4.8
    - pqctio
    - aimio
    - vtk =9.3.1

# test:
#   imports:
#     - vtkbone

about:
  home: https://github.com/Numerics88/vtkbone
  license: MIT
  license_family: MIT
  summary: 'VTK classes for bone FEA'
  description: |
    VTK classes for processing of finite element models derived from micro-CT. vtkbone was formerly vtkn88.
  dev_url: https://github.com/Numerics88/vtkbone