package:
  name: vtkbone
  version: 2.0.0
  # version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0
  string: "py{{ CONDA_PY }}"

# Refer to https://github.com/Numerics88/faimsuperbuild for requirements
requirements:
  build:
    - {{ compiler('c') }} # [not win]
    - {{ compiler('cxx') }} # [not win]
    - cmake >=3.12
    - ninja
    - gtest
    - boost =1.85.0
    - python {{ python }}
    - numpy >=1.24.3,<=1.26.4
    - vtk =9.3.1
    - pqctio
    - aimio
    - n88util
    - tbb-devel
    - eigen # [win]
    - expat # [win]
  run:
    - python {{ python }}
    - vtk =9.3.1
    - numpy >=1.24.3,<=1.26.4
    - pqctio
    - aimio
    - n88util
  test:
    imports:
      - vtkbone

about:
  home: https://github.com/Numerics88/vtkbone
  license: MIT
  license_family: MIT
  summary: 'VTK classes for bone FEA'
  description: |
    VTK classes for processing of finite element models derived from micro-CT. vtkbone was formerly vtkn88.
  dev_url: https://github.com/Numerics88/vtkbone