
package:
  name: vtkbone
  version: 1.1.0

source:
  path: ./../../

build:
  number: 0
  string: "py{{ CONDA_PY }}"

# Note, boost has an upperbound right now to hanlde cmake correctly
# and we need tbb-devel because of a CMake error upstream of VTK
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.12
    - ninja
    - gtest=1.8.0
    - python {{ python }}
    - boost >=1.57,<=1.67
    - libnetcdf >=4.7.1,<4.7.5
    - libcxx=11.1.0 # [osx]
    - n88util=2.0.0
    - pqctio=1.0.0
    - aimio=1.0.0
    - vtk =8.2
    - tbb-devel
    - nose
    - libxcrypt  # [linux]
  run:
    - python {{ python }}
    - boost >=1.57,<=1.67
    - libnetcdf >=4.7.1,<4.7.5
    - libcxx=11.1.0 # [osx]
    - n88util=2.0.0
    - pqctio=1.0.0
    - aimio=1.0.0
    - vtk =8.2

test:
  imports:
    - vtkbone

about:
  home: https://github.com/Numerics88/vtkbone
  license: MIT
  license_family: MIT
  summary: 'VTK classes for bone FEA'
  description: |
    VTK classes for processing of finite element models derived from micro-CT. vtkbone was formerly vtkn88.
  dev_url: https://github.com/Numerics88/vtkbone
