package:
  name: vtkbone
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0
  string: "py{{ CONDA_PY }}"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.12
    - ninja
    - gtest
    - python {{ python }}
    - boost 1.85
    - libnetcdf
    - pqctio
    - aimio
    - vtk =9.3.1
    - vtk-base =9.3.1
    - qt6-main <=6.8.2,<6.9.0
    - tbb-devel
    - nose
    # - {{ compiler('cxx') }}
    # - cmake >=3.19
    # - ninja
    # - gtest
    # - boost =1.85
    # - libnetcdf
    # - pqctio
    # - aimio
    # - vtk =9.3.1
    # - vtk-base =9.3.1
    # - qt6-main <=6.8.2,<6.9.0
    # - tbb-devel
    # - nose
    # - pugixml >=1.14,<1.15
    # - n88util
    # - libzlib >=1.3.1,<2.0
    # - icu >=75.1,<76.0
  run:
    - python {{ python }}
    - boost =1.85
    - libnetcdf
    - pqctio
    - aimio
    - vtk =9.3.1
    - vtk-base =9.3.1
  # host:
  #   - libcxx
  #   - pugixml >=1.14,<1.15
  #   - n88util
  #   - vtk =9.3.1

test:
  imports:
    - vtkbone

about:
  home: https://github.com/Numerics88/vtkbone
  license: MIT
  license_family: MIT
  summary: 'VTK classes for bone FEA'
  description: |
    VTK classes for processing of finite element models derived from micro-CT. vtkbone was formerly vtkn88.
  dev_url: https://github.com/Numerics88/vtkbone