
package:
  name: vtkbone
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0
  string: "py{{ CONDA_PY }}"

# Note, boost has an upperbound right now to hanlde cmake correctly
# and we need tbb-devel because of a CMake error upstream of VTK
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.12
    - ninja
    - gtest
    - python {{ python }}
    - boost >=1.57,<=1.67
    - libnetcdf =4.7
    - pqctio
    - aimio
    - vtk =8.2
    - tbb-devel
    - nose
  run:
    - python {{ python }}
    - boost >=1.57
    - libnetcdf =4.7
    - pqctio
    - aimio
    - vtk =8.2

test:
  imports:
    - vtkbone

about:
  home: https://github.com/Numerics88/vtkbone
  license: MIT
  license_family: MIT
  summary: 'VTK classes for bone FEA'
  description: |
    VTK classes for processing of finite element models derived from micro-CT. vtkbone was formerly vtkn88.
  dev_url: https://github.com/Numerics88/vtkbone
