
set(VTKBONE_MAJOR_VERSION 1)
set(VTKBONE_MINOR_VERSION 1)
set(VTKBONE_PATCH_VERSION 0)
set (VTKBONE_VERSION_TAG "devel")

# This is the version for CMake purposes, which must be of the form x.y.z
set(VTKBONE_VERSION
    ${VTKBONE_MAJOR_VERSION}.${VTKBONE_MINOR_VERSION}.${VTKBONE_PATCH_VERSION})

# This is the version for the code, which might include tags
set(VTKBONE_FULL_VERSION ${VTKBONE_MAJOR_VERSION}.${VTKBONE_MINOR_VERSION})
if (VTKBONE_PATCH_VERSION)
    set(VTKBONE_FULL_VERSION ${VTKBONE_FULL_VERSION}.${VTKBONE_PATCH_VERSION})
endif()
if (VTKBONE_VERSION_TAG)
    set(VTKBONE_FULL_VERSION ${VTKBONE_FULL_VERSION}-${VTKBONE_VERSION_TAG})
endif()
