
jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        sudo chown -R $USER $CONDA
    displayName: Add conda to path
  - bash: |
      sudo mkdir -p /opt/
      sudo chown -R $USER /opt/
      curl  -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz -o MacOSX10.9.sdk.tar.xz
      tar -xJf MacOSX10.9.sdk.tar.xz -C /opt/
    displayName: Download OSX SDK
  - script: conda create -y -n n88 conda-build
    displayName: Setup conda
  - script: |
        source activate n88
        conda-build -c Numerics88 -c conda-forge conda-recipe/vtkbone/ --variants "{'python': ['$(python.version)']}"
    displayName: Conda build
  - task: CopyFiles@2
    inputs:
        sourceFolder: /usr/local/miniconda/envs/n88/conda-bld/osx-64/
        contents: '*.tar.bz2'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy conda build
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: vtkbone-macOS-$(python.version)
    displayName: Publish artifact

