
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to path
  - script: conda create -y -n n88 conda-build
    displayName: Setup conda
  - script: |
        source activate n88
        conda-build -c Numerics88 -c conda-forge --python=$(python.version) conda-recipe/vtkbone/
    displayName: Conda build
  - task: CopyFiles@2
    inputs:
        sourceFolder: /usr/share/miniconda/envs/n88/conda-bld/linux-64/
        contents: '*.tar.bz2'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy conda build
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: vtkbone-Linux-$(python.version)
    displayName: Publish artifact

