# This workflow builds and publishes the conda package to the Numerics88 channel
# using the openalea/action-build-publish-anaconda action.
name: Conda Build And Publish

on:
    push:
        branches:
            - kean/rebuild-1.0
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Conda deployment
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # OS types: Windows x64, macOS 13 (last intel based runner), macOS latest (Apple silicon), and Ubuntu x64
            # ------------------------------------------------------
            os: ["macos-13"]
            python-minor-version: [6, 7]

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: kean/rebuild-1.0
              fetch-depth: 0

          - name: Download OSX 10.9 SDK tar and extract to /Library/Developer/CommandLineTools/SDKs
            if: startsWith(matrix.os, 'macos-13')
            run: |
              sudo mkdir -p /Library/Developer/CommandLineTools/SDKs
              sudo chown -R $USER /Library/Developer/CommandLineTools/SDKs
              curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz -o MacOSX10.9.sdk.tar.xz
              tar -xJf MacOSX10.9.sdk.tar.xz -C /Library/Developer/CommandLineTools/SDKs

          - name: Build and publish
            uses: openalea/action-build-publish-anaconda@v0.1.5
            with:
              conda: conda-recipe/vtkbone
              mamba: false
              python: ${{ matrix.python-minor-version }}
              numpy: '22'
              channels: Numerics88, conda-forge, defaults
              token: ${{ secrets.ANACONDA_TOKEN }}
              publish: true
              label: main

          
          
            